name: Deploy to S3

on:
  push:
    branches:
      - main
      - prod
  pull_request:
    branches:
      - prod

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up AWS CLI
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}

    - name: Upload App to Dev S3
      run: aws s3 sync ./source/index.html s3://${{secrets.DEV_BUCKET_NAME}}

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod' || (github.event_name == 'pull_request' && github.base_ref == 'refs/heads/prod')

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up AWS CLI
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}

    - name: Upload App to Prod S3
      run: aws s3 sync ./source/index.html s3://${{secrets.PROD_BUCKET_NAME}}
